unit unitCadGenerico;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, Buttons, ComCtrls, ExtCtrls;

  type
  TfrmCadGenerico=class(TForm)
    pnlGenerico: TPanel;
    Panel1: TPanel;
    dsGenerico: TDataSource;
    StatusBar1: TStatusBar;
    btnCancelar: TBitBtn;
    btnConfirmar: TBitBtn;
    procedure btnConfirmarClick(Sender : TObject);
    procedure btnCancelarClick(Sender : TObject);
    procedure FormActivate(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure Acento(Sender : TObject);
    procedure _PROC_00513D1F(Sender : TObject);
    procedure _PROC_00513E5C(Sender : TObject);
    procedure _PROC_00514014(Sender : TObject);
    procedure _PROC_00514044(Sender : TObject);
    procedure _PROC_0051404C(Sender : TObject);
    procedure _PROC_005143B9(Sender : TObject);
    procedure _PROC_00514415(Sender : TObject);
    procedure _PROC_00514444(Sender : TObject);
    procedure _PROC_0051444C(Sender : TObject);
    procedure _PROC_0051451E(Sender : TObject);
    procedure FormKeyPress(Sender: TObject; var Key: Char);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmCadGenerico: TfrmCadGenerico;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmCadGenerico.btnConfirmarClick(Sender : TObject);
begin
(*
00513BB4   55                     push    ebp
00513BB5   8BEC                   mov     ebp, esp
00513BB7   6A00                   push    $00
00513BB9   6A00                   push    $00
00513BBB   53                     push    ebx
00513BBC   56                     push    esi
00513BBD   57                     push    edi
00513BBE   8BD8                   mov     ebx, eax
00513BC0   33C0                   xor     eax, eax
00513BC2   55                     push    ebp

* Possible String Reference to: 'éXþîÿëë_^[YY]Ã'
|
00513BC3   681F3D5100             push    $00513D1F

***** TRY
|
00513BC8   64FF30                 push    dword ptr fs:[eax]
00513BCB   648920                 mov     fs:[eax], esp
00513BCE   33C0                   xor     eax, eax
00513BD0   55                     push    ebp
00513BD1   684E3C5100             push    $00513C4E

***** TRY
|
00513BD6   64FF30                 push    dword ptr fs:[eax]
00513BD9   648920                 mov     fs:[eax], esp
00513BDC   6A00                   push    $00
00513BDE   668B0D303D5100         mov     cx, word ptr [$00513D30]
00513BE5   B203                   mov     dl, $03

* Possible String Reference to: 'ATENÇÃO !Deseja realmente confirmar
|                                 esta operação?'
|
00513BE7   B83C3D5100             mov     eax, $00513D3C

|
00513BEC   E8CB5CF2FF             call    004398BC
00513BF1   83F806                 cmp     eax, +$06
00513BF4   754B                   jnz     00513C41

* Reference to control TfrmCadGenerico.dsGenerico : TDataSource
|
00513BF6   8B8300030000           mov     eax, [ebx+$0300]

* Reference to field TDataSource.DataSet : TDataSet
|
00513BFC   8B7030                 mov     esi, [eax+$30]

* Reference to field TDataSet.State : TDataSetState
|
00513BFF   8A869D000000           mov     al, byte ptr [esi+$009D]
00513C05   04FE                   add     al, -$02
00513C07   2C02                   sub     al, $02
00513C09   732F                   jnb     00513C3A
00513C0B   8BC6                   mov     eax, esi
00513C0D   8B10                   mov     edx, [eax]

* Reference to method TDataSet.Post()
|
00513C0F   FF924C020000           call    dword ptr [edx+$024C]

* Reference to control TfrmCadGenerico.dsGenerico : TDataSource
|
00513C15   8B8300030000           mov     eax, [ebx+$0300]

* Reference to field TDataSource.DataSet : TDataSet
|
00513C1B   8B4030                 mov     eax, [eax+$30]

* Reference to: DB.TDataSet.Close(TDataSet);
|
00513C1E   E85970F9FF             call    004AAC7C

* Reference to control TfrmCadGenerico.dsGenerico : TDataSource
|
00513C23   8B8300030000           mov     eax, [ebx+$0300]

* Reference to field TDataSource.DataSet : TDataSet
|
00513C29   8B4030                 mov     eax, [eax+$30]

* Reference to: DB.TDataSet.Open(TDataSet);
|
00513C2C   E83F70F9FF             call    004AAC70
00513C31   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00513C33   E8988CF7FF             call    0048C8D0
00513C38   EB07                   jmp     00513C41
00513C3A   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00513C3C   E88F8CF7FF             call    0048C8D0
00513C41   33C0                   xor     eax, eax
00513C43   5A                     pop     edx
00513C44   59                     pop     ecx
00513C45   59                     pop     ecx
00513C46   648910                 mov     fs:[eax], edx
00513C49   E9B6000000             jmp     00513D04

* Reference to: System.@HandleOnException;
|
00513C4E   E9A1FDEEFF             jmp     004039F4
00513C53   0100                   add     [eax], eax
00513C55   0000                   add     [eax], al
00513C57   D0644D00               shl     byte ptr [ebp+ecx*2+$00], 1
00513C5B   5F                     pop     edi
00513C5C   3C51                   cmp     al, $51
00513C5E   0089C333D28B           add     [ecx+$8BD233C3], cl
00513C64   C3                     ret


* Reference to: DBTables.EDBEngineError.GetError(EDBEngineError;Integer):TDBError;
|
00513C65   E8B660FCFF             call    004D9D20

* Reference to field TfrmCadGenerico.Owner : TComponent
|
00513C6A   668178040126           cmp     word ptr [eax+$04], $2601
00513C70   7517                   jnz     00513C89
00513C72   6A00                   push    $00
00513C74   668B0D703D5100         mov     cx, word ptr [$00513D70]
00513C7B   B202                   mov     dl, $02

* Possible String Reference to: 'ATENÇÃO !!! Código já existe no cad
|                                astro'
|
00513C7D   B87C3D5100             mov     eax, $00513D7C

|
00513C82   E8355CF2FF             call    004398BC
00513C87   EB76                   jmp     00513CFF
00513C89   33D2                   xor     edx, edx
00513C8B   8BC3                   mov     eax, ebx

* Reference to: DBTables.EDBEngineError.GetError(EDBEngineError;Integer):TDBError;
|
00513C8D   E88E60FCFF             call    004D9D20

* Reference to field TfrmCadGenerico.Owner : TComponent
|
00513C92   668178040333           cmp     word ptr [eax+$04], $3303
00513C98   7517                   jnz     00513CB1
00513C9A   6A00                   push    $00
00513C9C   668B0D703D5100         mov     cx, word ptr [$00513D70]
00513CA3   B202                   mov     dl, $02

* Possible String Reference to: 'ATENÇÃO !!! Campo(s) requeridos.'
|
00513CA5   B8B03D5100             mov     eax, $00513DB0

|
00513CAA   E80D5CF2FF             call    004398BC
00513CAF   EB4E                   jmp     00513CFF
00513CB1   6A00                   push    $00

* Possible String Reference to: 'ERRO NO SISTEMA !!! Código do erro '
|
00513CB3   68DC3D5100             push    $00513DDC
00513CB8   33D2                   xor     edx, edx
00513CBA   8BC3                   mov     eax, ebx

* Reference to: DBTables.EDBEngineError.GetError(EDBEngineError;Integer):TDBError;
|
00513CBC   E85F60FCFF             call    004D9D20
00513CC1   0FB74004               movzx   eax, word ptr [eax+$04]
00513CC5   8D55F8                 lea     edx, [ebp-$08]

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00513CC8   E88B52EFFF             call    00408F58
00513CCD   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ' = '
|
00513CD0   68083E5100             push    $00513E08
00513CD5   33D2                   xor     edx, edx
00513CD7   8BC3                   mov     eax, ebx

* Reference to: DBTables.EDBEngineError.GetError(EDBEngineError;Integer):TDBError;
|
00513CD9   E84260FCFF             call    004D9D20
00513CDE   FF700C                 push    dword ptr [eax+$0C]
00513CE1   8D45FC                 lea     eax, [ebp-$04]
00513CE4   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
00513CE9   E8EA08EFFF             call    004045D8
00513CEE   8B45FC                 mov     eax, [ebp-$04]
00513CF1   668B0D703D5100         mov     cx, word ptr [$00513D70]
00513CF8   B201                   mov     dl, $01

|
00513CFA   E8BD5BF2FF             call    004398BC

* Reference to: System.@DoneExcept;
|
00513CFF   E8F0FFEEFF             call    00403CF4
00513D04   33C0                   xor     eax, eax
00513D06   5A                     pop     edx
00513D07   59                     pop     ecx
00513D08   59                     pop     ecx
00513D09   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[YY]Ã'
|
00513D0C   68263D5100             push    $00513D26
00513D11   8D45F8                 lea     eax, [ebp-$08]
00513D14   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00513D19   E85E05EFFF             call    0040427C
00513D1E   C3                     ret

*)
end;

procedure TfrmCadGenerico.btnCancelarClick(Sender : TObject);
begin
(*
00513E0C   56                     push    esi
00513E0D   57                     push    edi
00513E0E   8BF0                   mov     esi, eax
00513E10   6A00                   push    $00
00513E12   668B0D5C3E5100         mov     cx, word ptr [$00513E5C]
00513E19   B203                   mov     dl, $03

* Possible String Reference to: 'ATENÇÃO !Deseja bealmente cancelar 
|                                esta operação?'
|
00513E1B   B8683E5100             mov     eax, $00513E68

|
00513E20   E8975AF2FF             call    004398BC
00513E25   83F806                 cmp     eax, +$06
00513E28   752F                   jnz     00513E59

* Reference to control TfrmCadGenerico.dsGenerico : TDataSource
|
00513E2A   8B8600030000           mov     eax, [esi+$0300]

* Reference to field TDataSource.DataSet : TDataSet
|
00513E30   8B7830                 mov     edi, [eax+$30]
00513E33   8A879D000000           mov     al, byte ptr [edi+$009D]
00513E39   04FE                   add     al, -$02
00513E3B   2C02                   sub     al, $02
00513E3D   7313                   jnb     00513E52
00513E3F   8BC7                   mov     eax, edi
00513E41   8B10                   mov     edx, [eax]

* Reference to method TDataSet.Cancel()
|
00513E43   FF920C020000           call    dword ptr [edx+$020C]
00513E49   8BC6                   mov     eax, esi

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00513E4B   E8808AF7FF             call    0048C8D0
00513E50   EB07                   jmp     00513E59
00513E52   8BC6                   mov     eax, esi

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00513E54   E8778AF7FF             call    0048C8D0
00513E59   5F                     pop     edi
00513E5A   5E                     pop     esi
00513E5B   C3                     ret

*)
end;

procedure TfrmCadGenerico.FormActivate(Sender : TObject);
begin
(*
00513E9C   55                     push    ebp
00513E9D   8BEC                   mov     ebp, esp
00513E9F   6A00                   push    $00
00513EA1   6A00                   push    $00
00513EA3   6A00                   push    $00
00513EA5   53                     push    ebx
00513EA6   8BD8                   mov     ebx, eax
00513EA8   33C0                   xor     eax, eax
00513EAA   55                     push    ebp

* Possible String Reference to: 'éTüîÿëã[‹å]Ã'
|
00513EAB   68233F5100             push    $00513F23

***** TRY
|
00513EB0   64FF30                 push    dword ptr fs:[eax]
00513EB3   648920                 mov     fs:[eax], esp
00513EB6   8D55F8                 lea     edx, [ebp-$08]
00513EB9   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00513EBB   E850B3F5FF             call    0046F210
00513EC0   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ' - Total de registros: '
|
00513EC3   68383F5100             push    $00513F38

* Reference to control TfrmCadGenerico.dsGenerico : TDataSource
|
00513EC8   8B8300030000           mov     eax, [ebx+$0300]

* Reference to field TDataSource.DataSet : TDataSet
|
00513ECE   8B4030                 mov     eax, [eax+$30]
00513ED1   8B10                   mov     edx, [eax]

* Reference to method TDataSet.GetRecordCount()
|
00513ED3   FF924C010000           call    dword ptr [edx+$014C]
00513ED9   8D55F4                 lea     edx, [ebp-$0C]

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00513EDC   E87750EFFF             call    00408F58
00513EE1   FF75F4                 push    dword ptr [ebp-$0C]

* Possible String Reference to: '  - [GABINETESys]'
|
00513EE4   68583F5100             push    $00513F58
00513EE9   8D45FC                 lea     eax, [ebp-$04]
00513EEC   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
00513EF1   E8E206EFFF             call    004045D8
00513EF6   8B55FC                 mov     edx, [ebp-$04]
00513EF9   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00513EFB   E840B3F5FF             call    0046F240
00513F00   33C0                   xor     eax, eax
00513F02   5A                     pop     edx
00513F03   59                     pop     ecx
00513F04   59                     pop     ecx
00513F05   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
00513F08   682A3F5100             push    $00513F2A
00513F0D   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
00513F10   E84303EFFF             call    00404258
00513F15   8D45F8                 lea     eax, [ebp-$08]
00513F18   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00513F1D   E85A03EFFF             call    0040427C
00513F22   C3                     ret


* Reference to: System.@HandleFinally;
|
00513F23   E954FCEEFF             jmp     00403B7C
00513F28   EBE3                   jmp     00513F0D

****** END
|
00513F2A   5B                     pop     ebx
00513F2B   8BE5                   mov     esp, ebp
00513F2D   5D                     pop     ebp
00513F2E   C3                     ret

*)
end;

procedure TfrmCadGenerico.FormClose(Sender : TObject);
begin
(*
00513F6C   33C0                   xor     eax, eax

|
00513F6E   E8557CFDFF             call    004EBBC8
00513F73   C3                     ret

*)
end;

procedure TfrmCadGenerico.FormShow(Sender : TObject);
begin
(*
00513F74   55                     push    ebp
00513F75   8BEC                   mov     ebp, esp
00513F77   6A00                   push    $00
00513F79   6A00                   push    $00
00513F7B   53                     push    ebx
00513F7C   8BD8                   mov     ebx, eax
00513F7E   33C0                   xor     eax, eax
00513F80   55                     push    ebp
00513F81   68CF3F5100             push    $00513FCF

***** TRY
|
00513F86   64FF30                 push    dword ptr fs:[eax]
00513F89   648920                 mov     fs:[eax], esp
00513F8C   8D45FC                 lea     eax, [ebp-$04]
00513F8F   50                     push    eax
00513F90   8D55F8                 lea     edx, [ebp-$08]
00513F93   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00513F95   E876B2F5FF             call    0046F210
00513F9A   8B45F8                 mov     eax, [ebp-$08]
00513F9D   B907000000             mov     ecx, $00000007
00513FA2   BA01000000             mov     edx, $00000001

* Reference to: System.@LStrCopy;
|
00513FA7   E8CC07EFFF             call    00404778
00513FAC   8B45FC                 mov     eax, [ebp-$04]

|
00513FAF   E8147CFDFF             call    004EBBC8
00513FB4   33C0                   xor     eax, eax
00513FB6   5A                     pop     edx
00513FB7   59                     pop     ecx
00513FB8   59                     pop     ecx
00513FB9   648910                 mov     fs:[eax], edx

****** FINALLY
|
00513FBC   68D63F5100             push    $00513FD6
00513FC1   8D45F8                 lea     eax, [ebp-$08]
00513FC4   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00513FC9   E8AE02EFFF             call    0040427C
00513FCE   C3                     ret


* Reference to: System.@HandleFinally;
|
00513FCF   E9A8FBEEFF             jmp     00403B7C
00513FD4   EBEB                   jmp     00513FC1

****** END
|
00513FD6   5B                     pop     ebx
00513FD7   59                     pop     ecx
00513FD8   59                     pop     ecx
00513FD9   5D                     pop     ebp
00513FDA   C3                     ret

*)
end;

procedure TfrmCadGenerico.Acento(Sender : TObject);
begin
(*
00513FDC   53                     push    ebx
00513FDD   8BD9                   mov     ebx, ecx
00513FDF   8A03                   mov     al, byte ptr [ebx]
00513FE1   2C08                   sub     al, $08
00513FE3   742B                   jz      00514010
00513FE5   04D8                   add     al, -$28
00513FE7   2C0A                   sub     al, $0A
00513FE9   7225                   jb      00514010
00513FEB   8A03                   mov     al, byte ptr [ebx]
00513FED   2C08                   sub     al, $08
00513FEF   741F                   jz      00514010
00513FF1   04C7                   add     al, -$39
00513FF3   2C1A                   sub     al, $1A
00513FF5   7219                   jb      00514010
00513FF7   8A03                   mov     al, byte ptr [ebx]
00513FF9   2C08                   sub     al, $08
00513FFB   7413                   jz      00514010
00513FFD   04A7                   add     al, -$59
00513FFF   2C1A                   sub     al, $1A
00514001   720D                   jb      00514010
00514003   803B20                 cmp     byte ptr [ebx], $20
00514006   7408                   jz      00514010

* Reference to: Classes.TStream.WriteComponentRes(TStream;AnsiString;TComponent);
|
00514008   E8C398EFFF             call    0040D8D0
0051400D   C60300                 mov     byte ptr [ebx], $00
00514010   5B                     pop     ebx
00514011   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_00513D1F(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00513D1F   E958FEEEFF             jmp     00403B7C

|
00513D24   EBEB                   jmp     00513D11
00513D26   5F                     pop     edi
00513D27   5E                     pop     esi
00513D28   5B                     pop     ebx
00513D29   59                     pop     ecx
00513D2A   59                     pop     ecx
00513D2B   5D                     pop     ebp
00513D2C   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_00513E5C(Sender : TObject);
begin
(*
00513E5C   0300                   add     eax, [eax]
00513E5E   0000                   add     [eax], al

*)
end;

procedure TfrmCadGenerico._PROC_00514014(Sender : TObject);
begin
(*
00514014   55                     push    ebp
00514015   8BEC                   mov     ebp, esp
00514017   33C0                   xor     eax, eax
00514019   55                     push    ebp

* Possible String Reference to: 'é>ûîÿëø]Ã‹Àƒ-ÀT'
|
0051401A   6839405100             push    $00514039

***** TRY
|
0051401F   64FF30                 push    dword ptr fs:[eax]
00514022   648920                 mov     fs:[eax], esp
00514025   FF0590C05400           inc     dword ptr [$0054C090]
0051402B   33C0                   xor     eax, eax
0051402D   5A                     pop     edx
0051402E   59                     pop     ecx
0051402F   59                     pop     ecx
00514030   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÀT'
|
00514033   6840405100             push    $00514040
00514038   C3                     ret


* Reference to: System.@HandleFinally;
|
00514039   E93EFBEEFF             jmp     00403B7C
0051403E   EBF8                   jmp     00514038

****** END
|
00514040   5D                     pop     ebp
00514041   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_00514044(Sender : TObject);
begin
(*
00514044   832D90C0540001         sub     dword ptr [$0054C090], +$01
0051404B   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_0051404C(Sender : TObject);
begin
(*
0051404C   68B65400F6             push    $F60054B6
00514051   FD                     std
00514052   0000                   add     [eax], al

*)
end;

procedure TfrmCadGenerico._PROC_005143B9(Sender : TObject);
begin
(*
005143B9   FD                     std
005143BA   0000                   add     [eax], al

*)
end;

procedure TfrmCadGenerico._PROC_00514415(Sender : TObject);
begin
(*
00514415   8BEC                   mov     ebp, esp
00514417   33C0                   xor     eax, eax
00514419   55                     push    ebp

* Possible String Reference to: 'é>÷îÿëø]Ã‹Àƒ-”ÀT'
|
0051441A   6839445100             push    $00514439

***** TRY
|
0051441F   64FF30                 push    dword ptr fs:[eax]
00514422   648920                 mov     fs:[eax], esp
00514425   FF0594C05400           inc     dword ptr [$0054C094]
0051442B   33C0                   xor     eax, eax
0051442D   5A                     pop     edx
0051442E   59                     pop     ecx
0051442F   59                     pop     ecx
00514430   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-”ÀT'
|
00514433   6840445100             push    $00514440
00514438   C3                     ret


* Reference to: System.@HandleFinally;
|
00514439   E93EF7EEFF             jmp     00403B7C
0051443E   EBF8                   jmp     00514438

****** END
|
00514440   5D                     pop     ebp
00514441   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_00514444(Sender : TObject);
begin
(*
00514444   832D94C0540001         sub     dword ptr [$0054C094], +$01
0051444B   C3                     ret

*)
end;

procedure TfrmCadGenerico._PROC_0051444C(Sender : TObject);
begin
(*
0051444C   98                     cwde 
0051444D   44                     inc     esp
0051444E   51                     push    ecx
0051444F   0000                   add     [eax], al

*)
end;

procedure TfrmCadGenerico._PROC_0051451E(Sender : TObject);
begin
(*
0051451E   47                     inc     edi
0051451F   00E4                   add     ah, ah
00514521   5A                     pop     edx
00514522   47                     inc     edi
00514523   0028                   add     [eax], ch
00514525   854800                 test    [eax+$00], ecx
00514528   2C9D                   sub     al, $9D
0051452A   48                     dec     eax
0051452B   00F4                   add     ah, dh
0051452D   2F                     das
0051452E   47                     inc     edi
0051452F   00F0                   add     al, dh
00514531   A9480050AD             test    eax, $AD500048
00514536   48                     dec     eax
00514537   000CAC                 add     [esp+ebp*4], cl
0051453A   48                     dec     eax
0051453B   008C3047009030         add     [eax+esi+$30900047], cl
00514542   47                     inc     edi
00514543   0088AE4800F0           add     [eax+$F00048AE], cl
00514549   2E47                   inc     edi
0051454B   00245C                 add     [esp+ebx*2], ah
0051454E   47                     inc     edi
0051454F   007CB548               add     [ebp+esi*4+$48], bh
00514553   0018                   add     [eax], bl
00514555   6E                     outsb
00514556   47                     inc     edi
00514557   006858                 add     [eax+$58], ch
0051455A   47                     inc     edi
0051455B   0090CA48001C           add     [eax+$1C0048CA], dl
00514561   7F48                   jnle    005145AB
00514563   00CC                   add     ah, cl
00514565   81480070BB4800         or      dword ptr [eax+$00], $0048BB70
0051456C   AC                     lodsb
0051456D   8B4800                 mov     ecx, [eax+$00]
00514570   288C480070CE48         sub     [eax+ecx*2+$48CE7000], cl
00514577   00E4                   add     ah, ah
00514579   884800                 mov     [eax+$00], cl
0051457C   74C9                   jz      00514547
0051457E   48                     dec     eax
0051457F   0054B048               add     [eax+esi*4+$48], dl
00514583   0028                   add     [eax], ch
00514585   CB                     ret

00514586   48                     dec     eax
00514587   000C96                 add     [esi+edx*4], cl
0051458A   48                     dec     eax
0051458B   0003                   add     [ebx], al
0051458D   00EE                   add     dh, ch
0051458F   45                     inc     ebp
00514590   51                     push    ecx
00514591   00F8                   add     al, bh
00514593   0200                   add     al, byte ptr [eax]
00514595   0000                   add     [eax], al

00514597   000449                 add     [ecx+ecx*2], al
0051459A   6E                     outsb
0051459B   666F                   outsw
0051459D   FC                     cld
0051459E   0200                   add     al, byte ptr [eax]
005145A0   0001                   add     [ecx], al
005145A2   000C43                 add     [ebx+eax*2], cl
005145A5   61                     popa
005145A6   6E                     outsb
005145A7   63656C                 arpl    [ebp+$6C], sp
005145AA   42                     inc     edx
005145AB   7574                   jnz     00514621
005145AD   746F                   jz      0051461E
005145AF   6E                     outsb
005145B0   0003                   add     [ebx], al
005145B2   0000                   add     [eax], al

005145B4   0200                   add     al, byte ptr [eax]
005145B6   0547617567             add     eax, +$67756147
005145BB   650100                 add     gs:[eax], eax
005145BE   1800                   sbb     [eax], al
005145C0   EC                     in      al, dx
005145C1   46                     inc     esi
005145C2   51                     push    ecx
005145C3   0011                   add     [ecx], dl
005145C5   43                     inc     ebx
005145C6   61                     popa
005145C7   6E                     outsb
005145C8   63656C                 arpl    [ebp+$6C], sp
005145CB   42                     inc     edx
005145CC   7574                   jnz     00514642
005145CE   746F                   jz      0051463F
005145D0   6E                     outsb
005145D1   43                     inc     ebx
005145D2   6C                     insb
005145D3   69636B01000004         imul    esp, [ebx+$6B], $04000001
005145DA   284651                 sub     [esi+$51], al
005145DD   000F                   add     [edi], cl
005145DF   54                     push    esp
005145E0   51                     push    ecx
005145E1   52                     push    edx
005145E2   50                     push    eax
005145E3   726F                   jb      00514654
005145E5   677265                 jb      0051464D
005145E8   7373                   jnb     0051465D
005145EA   46                     inc     esi
005145EB   6F                     outsd
005145EC   726D                   jb      0051465B
005145EE   0300                   add     eax, [eax]
005145F0   B0D6                   mov     al, $D6
005145F2   45                     inc     ebp
005145F3   0050FC                 add     [eax-$04], dl
005145F6   45                     inc     ebp
005145F7   00E4                   add     ah, ah
005145F9   6744                   inc     esp
005145FB   0000                   add     [eax], al

005145FD   46                     inc     esi
005145FE   51                     push    ecx
005145FF   0007                   add     [edi], al
00514601   0F54                   DB  $0F, $54  //
00514603   51                     push    ecx
00514604   52                     push    edx
00514605   50                     push    eax
00514606   726F                   jb      00514677
00514608   677265                 jb      00514670
0051460B   7373                   jnb     00514680
0051460D   46                     inc     esi
0051460E   6F                     outsd
0051460F   726D                   jb      0051467E
00514611   98                     cwde 
00514612   44                     inc     esp
00514613   51                     push    ecx
00514614   00985C48005E           add     [eax+$5E00485C], bl
0051461A   0008                   add     [eax], cl
0051461C   51                     push    ecx
0051461D   52                     push    edx
0051461E   50                     push    eax
0051461F   7267                   jb      00514688
00514621   7265                   jb      00514688
00514623   7300                   jnb     00514625
00514625   008BC0558BEC           add     [ebx+$EC8B55C0], cl
0051462B   6A00                   push    $00
0051462D   6A00                   push    $00
0051462F   6A00                   push    $00
00514631   53                     push    ebx
00514632   56                     push    esi
00514633   8BD8                   mov     ebx, eax
00514635   33C0                   xor     eax, eax
00514637   55                     push    ebp

* Possible String Reference to: 'é¥ôîÿëë^[‹å]Ã'
|
00514638   68D2465100             push    $005146D2

***** TRY
|
0051463D   64FF30                 push    dword ptr fs:[eax]
00514640   648920                 mov     fs:[eax], esp
00514643   8B8304030000           mov     eax, [ebx+$0304]
00514649   8B4878                 mov     ecx, [eax+$78]
0051464C   8BC1                   mov     eax, ecx
0051464E   BE05000000             mov     esi, $00000005
00514653   99                     cdq
00514654   F7FE                   idiv    esi 
00514656   85D2                   test    edx, edx
00514658   755D                   jnz     005146B7
0051465A   8BD1                   mov     edx, ecx
0051465C   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: ComCtrls.TProgressBar.SetPosition(TProgressBar;Integer);
|
00514662   E8A5DEF3FF             call    0045250C
00514667   8D55F8                 lea     edx, [ebp-$08]
0051466A   8B8304030000           mov     eax, [ebx+$0304]
00514670   8B4078                 mov     eax, [eax+$78]

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00514673   E8E048EFFF             call    00408F58
00514678   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: '% '
|
0051467B   68E8465100             push    $005146E8
00514680   8D55F4                 lea     edx, [ebp-$0C]
00514683   A1C89C5400             mov     eax, dword ptr [$00549CC8]

* Reference to: System.LoadResString(PResStringRec):String;
|
00514688   E8431EEFFF             call    004064D0
0051468D   FF75F4                 push    dword ptr [ebp-$0C]
00514690   8D45FC                 lea     eax, [ebp-$04]
00514693   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
00514698   E83BFFEEFF             call    004045D8
0051469D   8B55FC                 mov     edx, [ebp-$04]
005146A0   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
005146A6   E895ABF5FF             call    0046F240

* Reference to TApplication instance
|
005146AB   A1ECA35400             mov     eax, dword ptr [$0054A3EC]
005146B0   8B00                   mov     eax, [eax]

* Reference to: Forms.TApplication.ProcessMessages(TApplication);
|
005146B2   E825B8F7FF             call    0048FEDC
005146B7   33C0                   xor     eax, eax
005146B9   5A                     pop     edx
005146BA   59                     pop     ecx
005146BB   59                     pop     ecx
005146BC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
005146BF   68D9465100             push    $005146D9
005146C4   8D45F4                 lea     eax, [ebp-$0C]
005146C7   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
005146CC   E8ABFBEEFF             call    0040427C
005146D1   C3                     ret

*)
end;

procedure TfrmCadGenerico.FormKeyPress(Sender: TObject; var Key: Char);
begin
  if key = #13
   then begin
     key := #0;
     PostMessage(handle, WM_KEYDOWN, VK_TAB, 1);
   end;
end;

end.