unit unitUsuario;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmUsuario=class(TForm)
    procedure cboCampoExit(Sender : TObject);
    procedure btnIncluirClick(Sender : TObject);
    procedure btnAlterarClick(Sender : TObject);
    procedure btnImpClick(Sender : TObject);
    procedure _PROC_0053CD41(Sender : TObject);
    procedure _PROC_0053CE0C(Sender : TObject);
    procedure _PROC_0053CE3C(Sender : TObject);
    procedure _PROC_0053CE45(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmUsuario: TfrmUsuario;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmUsuario.cboCampoExit(Sender : TObject);
begin
(*
0053CC6C   55                     push    ebp
0053CC6D   8BEC                   mov     ebp, esp
0053CC6F   6A00                   push    $00
0053CC71   6A00                   push    $00
0053CC73   6A00                   push    $00
0053CC75   53                     push    ebx
0053CC76   8BD8                   mov     ebx, eax
0053CC78   33C0                   xor     eax, eax
0053CC7A   55                     push    ebp
0053CC7B   682CCD5300             push    $0053CD2C

***** TRY
|
0053CC80   64FF30                 push    dword ptr fs:[eax]
0053CC83   648920                 mov     fs:[eax], esp
0053CC86   8D55FC                 lea     edx, [ebp-$04]

* Reference to field TfrmUsuario.OFFS_0368
|
0053CC89   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0053CC8F   E87C25F3FF             call    0046F210
0053CC94   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'Usuário'
|
0053CC97   BA40CD5300             mov     edx, $0053CD40

* Reference to: System.@LStrCmp;
|
0053CC9C   E8C379ECFF             call    00404664
0053CCA1   7512                   jnz     0053CCB5

* Possible String Reference to: 'usuario'
|
0053CCA3   BA50CD5300             mov     edx, $0053CD50

* Reference to field TfrmUsuario.OFFS_0388
|
0053CCA8   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0053CCAE   E88D25F3FF             call    0046F240
0053CCB3   EB5C                   jmp     0053CD11
0053CCB5   8D55F8                 lea     edx, [ebp-$08]

* Reference to field TfrmUsuario.OFFS_0368
|
0053CCB8   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0053CCBE   E84D25F3FF             call    0046F210
0053CCC3   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'Senha'
|
0053CCC6   BA60CD5300             mov     edx, $0053CD60

* Reference to: System.@LStrCmp;
|
0053CCCB   E89479ECFF             call    00404664
0053CCD0   7512                   jnz     0053CCE4

* Possible String Reference to: 'senha'
|
0053CCD2   BA70CD5300             mov     edx, $0053CD70

* Reference to field TfrmUsuario.OFFS_0388
|
0053CCD7   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0053CCDD   E85E25F3FF             call    0046F240
0053CCE2   EB2D                   jmp     0053CD11
0053CCE4   8D55F4                 lea     edx, [ebp-$0C]

* Reference to field TfrmUsuario.OFFS_0368
|
0053CCE7   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0053CCED   E81E25F3FF             call    0046F210
0053CCF2   8B45F4                 mov     eax, [ebp-$0C]

* Possible String Reference to: 'Grupo'
|
0053CCF5   BA80CD5300             mov     edx, $0053CD80

* Reference to: System.@LStrCmp;
|
0053CCFA   E86579ECFF             call    00404664
0053CCFF   7510                   jnz     0053CD11

* Possible String Reference to: 'adm'
|
0053CD01   BA90CD5300             mov     edx, $0053CD90

* Reference to field TfrmUsuario.OFFS_0388
|
0053CD06   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0053CD0C   E82F25F3FF             call    0046F240
0053CD11   33C0                   xor     eax, eax
0053CD13   5A                     pop     edx
0053CD14   59                     pop     ecx
0053CD15   59                     pop     ecx
0053CD16   648910                 mov     fs:[eax], edx

****** FINALLY
|
0053CD19   6833CD5300             push    $0053CD33
0053CD1E   8D45F4                 lea     eax, [ebp-$0C]
0053CD21   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0053CD26   E85175ECFF             call    0040427C
0053CD2B   C3                     ret


* Reference to: System.@HandleFinally;
|
0053CD2C   E94B6EECFF             jmp     00403B7C
0053CD31   EBEB                   jmp     0053CD1E

****** END
|
0053CD33   5B                     pop     ebx
0053CD34   8BE5                   mov     esp, ebp
0053CD36   5D                     pop     ebp
0053CD37   C3                     ret

*)
end;

procedure TfrmUsuario.btnIncluirClick(Sender : TObject);
begin
(*
0053CD94   53                     push    ebx
0053CD95   8BD8                   mov     ebx, eax
0053CD97   8BC3                   mov     eax, ebx

* Reference to : TfrmGenerico.btnIncluirClick()
|
0053CD99   E8B266FDFF             call    00513450
0053CD9E   8BD3                   mov     edx, ebx

* Reference to class TfrmCadUsuario
|
0053CDA0   A118C85300             mov     eax, dword ptr [$0053C818]

|
0053CDA5   E8D6EDFAFF             call    004EBB80
0053CDAA   5B                     pop     ebx
0053CDAB   C3                     ret

*)
end;

procedure TfrmUsuario.btnAlterarClick(Sender : TObject);
begin
(*
0053CDAC   53                     push    ebx
0053CDAD   8BD8                   mov     ebx, eax
0053CDAF   8BC3                   mov     eax, ebx

* Reference to : TfrmGenerico.btnAlterarClick()
|
0053CDB1   E8AA66FDFF             call    00513460
0053CDB6   8BD3                   mov     edx, ebx

* Reference to class TfrmCadUsuario
|
0053CDB8   A118C85300             mov     eax, dword ptr [$0053C818]

|
0053CDBD   E8BEEDFAFF             call    004EBB80
0053CDC2   5B                     pop     ebx
0053CDC3   C3                     ret

*)
end;

procedure TfrmUsuario.btnImpClick(Sender : TObject);
begin
(*
0053CDC4   55                     push    ebp
0053CDC5   8BEC                   mov     ebp, esp
0053CDC7   53                     push    ebx
0053CDC8   33D2                   xor     edx, edx
0053CDCA   55                     push    ebp

* Possible String Reference to: 'éumìÿëø[]ÃU‹ì3ÀUh1ÎS'
|
0053CDCB   6802CE5300             push    $0053CE02

***** TRY
|
0053CDD0   64FF32                 push    dword ptr fs:[edx]
0053CDD3   648922                 mov     fs:[edx], esp
0053CDD6   8BC8                   mov     ecx, eax
0053CDD8   B201                   mov     dl, $01

* Reference to class TfrmAguarde
|
0053CDDA   A194BC4E00             mov     eax, dword ptr [$004EBC94]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0053CDDF   E83CB9F4FF             call    00488720
0053CDE4   8BD8                   mov     ebx, eax
0053CDE6   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Show(TCustomForm);
|
0053CDE8   E88BFCF4FF             call    0048CA78
0053CDED   8BC3                   mov     eax, ebx

* Reference to: System.TObject.Free(TObject);
|
0053CDEF   E8F465ECFF             call    004033E8
0053CDF4   33C0                   xor     eax, eax
0053CDF6   5A                     pop     edx
0053CDF7   59                     pop     ecx
0053CDF8   59                     pop     ecx
0053CDF9   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[]ÃU‹ì3ÀUh1ÎS'
|
0053CDFC   6809CE5300             push    $0053CE09
0053CE01   C3                     ret


* Reference to: System.@HandleFinally;
|
0053CE02   E9756DECFF             jmp     00403B7C
0053CE07   EBF8                   jmp     0053CE01

****** END
|
0053CE09   5B                     pop     ebx
0053CE0A   5D                     pop     ebp
0053CE0B   C3                     ret

*)
end;

procedure TfrmUsuario._PROC_0053CD41(Sender : TObject);
begin
(*
0053CD41   7375                   jnb     0053CDB8
0053CD43   E172                   loope   +$72
0053CD45   696F00FFFFFFFF         imul    ebp, [edi+$00], $FFFFFFFF
0053CD4C   07                     pop     es
0053CD4D   0000                   add     [eax], al

0053CD4F   007573                 add     [ebp+$73], dh
0053CD52   7561                   jnz     0053CDB5
0053CD54   7269                   jb      0053CDBF
0053CD56   6F                     outsd
0053CD57   00FF                   add     bh, bh
0053CD59   FFFF                   DB  $FF, $FF  //      
0053CD5B   FF0500000053           inc     dword ptr [$53000000]
0053CD61   656E                   outsb
0053CD63   6861000000             push    $00000061
0053CD68   FFFF                   DB  $FF, $FF  //      
0053CD6A   FFFF                   DB  $FF, $FF  //      
0053CD6C   0500000073             add     eax, +$73000000
0053CD71   656E                   outsb
0053CD73   6861000000             push    $00000061
0053CD78   FFFF                   DB  $FF, $FF  //      
0053CD7A   FFFF                   DB  $FF, $FF  //      
0053CD7C   0500000047             add     eax, +$47000000
0053CD81   7275                   jb      0053CDF8
0053CD83   706F                   jo      0053CDF4
0053CD85   0000                   add     [eax], al

0053CD87   00FF                   add     bh, bh
0053CD89   FFFF                   DB  $FF, $FF  //      
0053CD8B   FF03                   inc     dword ptr [ebx]
0053CD8D   0000                   add     [eax], al

0053CD8F   006164                 add     [ecx+$64], ah
0053CD92   6D                     insd
0053CD93   00538B                 add     [ebx-$75], dl
0053CD96   D88BC3E8B266           fmul    dword ptr [ebx+$66B2E8C3]
0053CD9C   FD                     std
0053CD9D   FF8BD3A118C8           dec     dword ptr [ebx+$C818A1D3]
0053CDA3   53                     push    ebx
0053CDA4   00E8                   add     al, ch
0053CDA6   D6                     DB  $D6  //
0053CDA7   ED                     in      eax, dx
0053CDA8   FA                     cli
0053CDA9   FF5BC3                 call    [ebx-$3D]
0053CDAC   53                     push    ebx
0053CDAD   8BD8                   mov     ebx, eax
0053CDAF   8BC3                   mov     eax, ebx

* Reference to : TfrmGenerico.btnAlterarClick()
|
0053CDB1   E8AA66FDFF             call    00513460
0053CDB6   8BD3                   mov     edx, ebx

* Reference to class TfrmCadUsuario
|
0053CDB8   A118C85300             mov     eax, dword ptr [$0053C818]

|
0053CDBD   E8BEEDFAFF             call    004EBB80
0053CDC2   5B                     pop     ebx
0053CDC3   C3                     ret

0053CDC4   55                     push    ebp
0053CDC5   8BEC                   mov     ebp, esp
0053CDC7   53                     push    ebx
0053CDC8   33D2                   xor     edx, edx
0053CDCA   55                     push    ebp

* Possible String Reference to: 'éumìÿëø[]ÃU‹ì3ÀUh1ÎS'
|
0053CDCB   6802CE5300             push    $0053CE02

***** TRY
|
0053CDD0   64FF32                 push    dword ptr fs:[edx]
0053CDD3   648922                 mov     fs:[edx], esp
0053CDD6   8BC8                   mov     ecx, eax
0053CDD8   B201                   mov     dl, $01

* Reference to class TfrmAguarde
|
0053CDDA   A194BC4E00             mov     eax, dword ptr [$004EBC94]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0053CDDF   E83CB9F4FF             call    00488720
0053CDE4   8BD8                   mov     ebx, eax
0053CDE6   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Show(TCustomForm);
|
0053CDE8   E88BFCF4FF             call    0048CA78
0053CDED   8BC3                   mov     eax, ebx

* Reference to: System.TObject.Free(TObject);
|
0053CDEF   E8F465ECFF             call    004033E8
0053CDF4   33C0                   xor     eax, eax
0053CDF6   5A                     pop     edx
0053CDF7   59                     pop     ecx
0053CDF8   59                     pop     ecx
0053CDF9   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[]ÃU‹ì3ÀUh1ÎS'
|
0053CDFC   6809CE5300             push    $0053CE09
0053CE01   C3                     ret

*)
end;

procedure TfrmUsuario._PROC_0053CE0C(Sender : TObject);
begin
(*
0053CE0C   55                     push    ebp
0053CE0D   8BEC                   mov     ebp, esp
0053CE0F   33C0                   xor     eax, eax
0053CE11   55                     push    ebp

* Possible String Reference to: 'éFmìÿëø]Ã‹Àƒ-ÀÁT'
|
0053CE12   6831CE5300             push    $0053CE31

***** TRY
|
0053CE17   64FF30                 push    dword ptr fs:[eax]
0053CE1A   648920                 mov     fs:[eax], esp
0053CE1D   FF05C0C15400           inc     dword ptr [$0054C1C0]
0053CE23   33C0                   xor     eax, eax
0053CE25   5A                     pop     edx
0053CE26   59                     pop     ecx
0053CE27   59                     pop     ecx
0053CE28   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÀÁT'
|
0053CE2B   6838CE5300             push    $0053CE38
0053CE30   C3                     ret


* Reference to: System.@HandleFinally;
|
0053CE31   E9466DECFF             jmp     00403B7C
0053CE36   EBF8                   jmp     0053CE30

****** END
|
0053CE38   5D                     pop     ebp
0053CE39   C3                     ret

*)
end;

procedure TfrmUsuario._PROC_0053CE3C(Sender : TObject);
begin
(*
0053CE3C   832DC0C1540001         sub     dword ptr [$0054C1C0], +$01
0053CE43   C3                     ret

*)
end;

procedure TfrmUsuario._PROC_0053CE45(Sender : TObject);
begin
(*
0053CE45   CE                     into
0053CE46   53                     push    ebx
0053CE47   0000                   add     [eax], al

*)
end;

end.