unit UnitCadPessoa;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmCadPessoa=class(TForm)
    Panel2: TPanel;
    Label1: TLabel;
    Label4: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Label3: TLabel;
    Label14: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    Label6: TLabel;
    Label5: TLabel;
    Label64: TLabel;
    Label62: TLabel;
    Label63: TLabel;
    Label2: TLabel;
    Label13: TLabel;
    DBEdit3: TDBEdit;
    DBEdit6: TDBEdit;
    DBEdit13: TDBEdit;
    DBEdit14: TDBEdit;
    DBEdit9: TDBEdit;
    DBEdit4: TDBEdit;
    DBComboBox1: TDBComboBox;
    DBLookupComboBox1: TDBLookupComboBox;
    DBEdit53: TDBEdit;
    DBComboBox5: TDBComboBox;
    DBComboBox6: TDBComboBox;
    DBEdit2: TDBEdit;
    DBEdit5: TDBEdit;
    Panel4: TPanel;
    pgcItens: TPageControl;
    tbsDoc: TTabSheet;
    Label18: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    Label21: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label32: TLabel;
    DBEdit10: TDBEdit;
    DBEdit11: TDBEdit;
    DBEdit17: TDBEdit;
    DBEdit18: TDBEdit;
    DBEdit19: TDBEdit;
    DBEdit20: TDBEdit;
    DBEdit29: TDBEdit;
    tbsObs: TTabSheet;
    Panel10: TPanel;
    Panel11: TPanel;
    DBMemo2: TDBMemo;
    TabSheet1: TTabSheet;
    ImageList1: TImageList;
    ToolBar2: TToolBar;
    ToolButton2: TToolButton;
    ToolButton4: TToolButton;
    ToolButton5: TToolButton;
    ToolButton6: TToolButton;
    ToolButton8: TToolButton;
    ToolButton9: TToolButton;
    ToolButton10: TToolButton;
    ToolButton11: TToolButton;
    Button2: TToolButton;
    Panel3: TPanel;
    DBGrid1: TDBGrid;
    dssolicitacao: TDataSource;
    DBText1: TDBText;
    DBEdit1: TDBEdit;
    DBEdit12: TDBEdit;
    DBEdit15: TDBEdit;
    Label12: TLabel;
    DBRadioGroup1: TDBRadioGroup;
    DBLookupComboBox2: TDBLookupComboBox;
    dsmunicipio: TDataSource;
    DBLookupComboBox3: TDBLookupComboBox;
    dsbairro: TDataSource;
    procedure ToolButton4Click(Sender : TObject);
    procedure ToolButton5Click(Sender : TObject);
    procedure DBEdit3KeyPress(Sender : TObject);
    procedure DBMemo2KeyPress(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_0053909C(Sender : TObject);
    procedure _PROC_005390CC(Sender : TObject);
    procedure _PROC_005390D4(Sender : TObject);
    procedure _PROC_005391A6(Sender : TObject);
    procedure _PROC_005395CF(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmCadPessoa: TfrmCadPessoa;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmCadPessoa.ToolButton4Click(Sender : TObject);
begin
(*
00538F74   53                     push    ebx
00538F75   8BD8                   mov     ebx, eax

* Reference to field TfrmCadPessoa.OFFS_0300
|
00538F77   8B8300030000           mov     eax, [ebx+$0300]
00538F7D   8B4030                 mov     eax, [eax+$30]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
00538F80   E8BB44F7FF             call    004AD440

* Reference to control TfrmCadPessoa.dssolicitacao : TDataSource
|
00538F85   8B8314040000           mov     eax, [ebx+$0414]

* Reference to field TDataSource.DataSet : TDataSet
|
00538F8B   8B4030                 mov     eax, [eax+$30]

* Reference to: DB.TDataSet.Insert(TDataSet);
|
00538F8E   E84145F7FF             call    004AD4D4
00538F93   8BD3                   mov     edx, ebx

* Reference to class TfrmItemPessoa
|
00538F95   A1A0845300             mov     eax, dword ptr [$005384A0]

|
00538F9A   E8E12BFBFF             call    004EBB80
00538F9F   5B                     pop     ebx
00538FA0   C3                     ret

*)
end;

procedure TfrmCadPessoa.ToolButton5Click(Sender : TObject);
begin
(*
00538FA4   53                     push    ebx
00538FA5   8BD8                   mov     ebx, eax

* Reference to control TfrmCadPessoa.dssolicitacao : TDataSource
|
00538FA7   8B8314040000           mov     eax, [ebx+$0414]

* Reference to field TDataSource.DataSet : TDataSet
|
00538FAD   8B4030                 mov     eax, [eax+$30]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
00538FB0   E88B44F7FF             call    004AD440
00538FB5   8BD3                   mov     edx, ebx

* Reference to class TfrmItemPessoa
|
00538FB7   A1A0845300             mov     eax, dword ptr [$005384A0]

|
00538FBC   E8BF2BFBFF             call    004EBB80
00538FC1   5B                     pop     ebx
00538FC2   C3                     ret

*)
end;

procedure TfrmCadPessoa.DBEdit3KeyPress(Sender : TObject);
begin
(*
00538FC4   53                     push    ebx
00538FC5   8BD9                   mov     ebx, ecx
00538FC7   8A03                   mov     al, byte ptr [ebx]
00538FC9   2C08                   sub     al, $08
00538FCB   742B                   jz      00538FF8
00538FCD   04D8                   add     al, -$28
00538FCF   2C0A                   sub     al, $0A
00538FD1   7225                   jb      00538FF8
00538FD3   8A03                   mov     al, byte ptr [ebx]
00538FD5   2C08                   sub     al, $08
00538FD7   741F                   jz      00538FF8
00538FD9   04C7                   add     al, -$39
00538FDB   2C1A                   sub     al, $1A
00538FDD   7219                   jb      00538FF8
00538FDF   8A03                   mov     al, byte ptr [ebx]
00538FE1   2C08                   sub     al, $08
00538FE3   7413                   jz      00538FF8
00538FE5   04A7                   add     al, -$59
00538FE7   2C1A                   sub     al, $1A
00538FE9   720D                   jb      00538FF8
00538FEB   803B20                 cmp     byte ptr [ebx], $20
00538FEE   7408                   jz      00538FF8

* Reference to: Classes.TStream.WriteComponentRes(TStream;AnsiString;TComponent);
|
00538FF0   E8DB48EDFF             call    0040D8D0
00538FF5   C60300                 mov     byte ptr [ebx], $00
00538FF8   5B                     pop     ebx
00538FF9   C3                     ret

*)
end;

procedure TfrmCadPessoa.DBMemo2KeyPress(Sender : TObject);
begin
(*
00538FFC   53                     push    ebx
00538FFD   8BD9                   mov     ebx, ecx
00538FFF   8A03                   mov     al, byte ptr [ebx]
00539001   2C08                   sub     al, $08
00539003   742B                   jz      00539030
00539005   04D8                   add     al, -$28
00539007   2C0A                   sub     al, $0A
00539009   7225                   jb      00539030
0053900B   8A03                   mov     al, byte ptr [ebx]
0053900D   2C08                   sub     al, $08
0053900F   741F                   jz      00539030
00539011   04C7                   add     al, -$39
00539013   2C1A                   sub     al, $1A
00539015   7219                   jb      00539030
00539017   8A03                   mov     al, byte ptr [ebx]
00539019   2C08                   sub     al, $08
0053901B   7413                   jz      00539030
0053901D   04A7                   add     al, -$59
0053901F   2C1A                   sub     al, $1A
00539021   720D                   jb      00539030
00539023   803B20                 cmp     byte ptr [ebx], $20
00539026   7408                   jz      00539030

* Reference to: Classes.TStream.WriteComponentRes(TStream;AnsiString;TComponent);
|
00539028   E8A348EDFF             call    0040D8D0
0053902D   C60300                 mov     byte ptr [ebx], $00
00539030   5B                     pop     ebx
00539031   C3                     ret

*)
end;

procedure TfrmCadPessoa.FormShow(Sender : TObject);
begin
(*
00539034   53                     push    ebx
00539035   56                     push    esi
00539036   57                     push    edi
00539037   8BF0                   mov     esi, eax
00539039   8BC6                   mov     eax, esi

* Reference to : TfrmCadGenerico.FormShow()
|
0053903B   E834AFFDFF             call    00513F74

* Reference to field TfrmCadPessoa.OFFS_0300
|
00539040   8B8600030000           mov     eax, [esi+$0300]
00539046   8B4030                 mov     eax, [eax+$30]
00539049   8A809D000000           mov     al, byte ptr [eax+$009D]
0053904F   2C03                   sub     al, $03
00539051   7544                   jnz     00539097
00539053   BF02000000             mov     edi, $00000002
00539058   8BCE                   mov     ecx, esi
0053905A   B201                   mov     dl, $01

* Reference to class TTabSheet
|
0053905C   A138344400             mov     eax, dword ptr [$00443438]

* Reference to : TTabStrings._PROC_0044B350()
|
00539061   E8EA22F1FF             call    0044B350
00539066   8BD8                   mov     ebx, eax

* Reference to control TfrmCadPessoa.pgcItens : TPageControl
|
00539068   8B968C030000           mov     edx, [esi+$038C]
0053906E   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TTabSheet.SetPageControl(TTabSheet;TPageControl);
|
00539070   E8B324F1FF             call    0044B528
00539075   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TTabSheet.GetPageIndex(TTabSheet):Integer;
|
00539077   E8C823F1FF             call    0044B444
0053907C   2501000080             and     eax, $80000001
00539081   7905                   jns     00539088
00539083   48                     dec     eax
00539084   83C8FE                 or      eax, -$02
00539087   40                     inc     eax
00539088   85C0                   test    eax, eax
0053908A   0F94C2                 setz    dl
0053908D   8BC3                   mov     eax, ebx

* Reference to: ComCtrls.TTabSheet.SetTabVisible(TTabSheet;Boolean);
|
0053908F   E8A025F1FF             call    0044B634
00539094   4F                     dec     edi
00539095   75C1                   jnz     00539058
00539097   5F                     pop     edi
00539098   5E                     pop     esi
00539099   5B                     pop     ebx
0053909A   C3                     ret

*)
end;

procedure TfrmCadPessoa._PROC_0053909C(Sender : TObject);
begin
(*
0053909C   55                     push    ebp
0053909D   8BEC                   mov     ebp, esp
0053909F   33C0                   xor     eax, eax
005390A1   55                     push    ebp

* Possible String Reference to: 'é¶ªìÿëø]Ã‹Àƒ-ˆÁT'
|
005390A2   68C1905300             push    $005390C1

***** TRY
|
005390A7   64FF30                 push    dword ptr fs:[eax]
005390AA   648920                 mov     fs:[eax], esp
005390AD   FF0588C15400           inc     dword ptr [$0054C188]
005390B3   33C0                   xor     eax, eax
005390B5   5A                     pop     edx
005390B6   59                     pop     ecx
005390B7   59                     pop     ecx
005390B8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ˆÁT'
|
005390BB   68C8905300             push    $005390C8
005390C0   C3                     ret


* Reference to: System.@HandleFinally;
|
005390C1   E9B6AAECFF             jmp     00403B7C
005390C6   EBF8                   jmp     005390C0

****** END
|
005390C8   5D                     pop     ebp
005390C9   C3                     ret

*)
end;

procedure TfrmCadPessoa._PROC_005390CC(Sender : TObject);
begin
(*
005390CC   832D88C1540001         sub     dword ptr [$0054C188], +$01
005390D3   C3                     ret

*)
end;

procedure TfrmCadPessoa._PROC_005390D4(Sender : TObject);
begin
(*
005390D4   209153000000           and     [ecx+$0053], dl
005390DA   0000                   add     [eax], al

*)
end;

procedure TfrmCadPessoa._PROC_005391A6(Sender : TObject);
begin
(*
005391A6   47                     inc     edi
005391A7   00E4                   add     ah, ah
005391A9   5A                     pop     edx
005391AA   47                     inc     edi
005391AB   0028                   add     [eax], ch
005391AD   854800                 test    [eax+$00], ecx
005391B0   2C9D                   sub     al, $9D
005391B2   48                     dec     eax
005391B3   00F4                   add     ah, dh
005391B5   2F                     das
005391B6   47                     inc     edi
005391B7   00F0                   add     al, dh
005391B9   A9480050AD             test    eax, $AD500048
005391BE   48                     dec     eax
005391BF   000CAC                 add     [esp+ebp*4], cl
005391C2   48                     dec     eax
005391C3   008C3047009030         add     [eax+esi+$30900047], cl
005391CA   47                     inc     edi
005391CB   0088AE4800F0           add     [eax+$F00048AE], cl
005391D1   2E47                   inc     edi
005391D3   00245C                 add     [esp+ebx*2], ah
005391D6   47                     inc     edi
005391D7   007CB548               add     [ebp+esi*4+$48], bh
005391DB   0018                   add     [eax], bl
005391DD   6E                     outsb
005391DE   47                     inc     edi
005391DF   006858                 add     [eax+$58], ch
005391E2   47                     inc     edi
005391E3   0090CA48001C           add     [eax+$1C0048CA], dl
005391E9   7F48                   jnle    00539233
005391EB   00CC                   add     ah, cl
005391ED   81480070BB4800         or      dword ptr [eax+$00], $0048BB70
005391F4   AC                     lodsb
005391F5   8B4800                 mov     ecx, [eax+$00]
005391F8   288C480070CE48         sub     [eax+ecx*2+$48CE7000], cl
005391FF   00E4                   add     ah, ah
00539201   884800                 mov     [eax+$00], cl
00539204   74C9                   jz      005391CF
00539206   48                     dec     eax
00539207   0054B048               add     [eax+esi*4+$48], dl
0053920B   0028                   add     [eax], ch
0053920D   CB                     ret

0053920E   48                     dec     eax
0053920F   000C96                 add     [esi+edx*4], cl
00539212   48                     dec     eax
00539213   006D00                 add     [ebp+$00], ch
00539216   BF9A5300F8             mov     edi, $F800539A
0053921B   0200                   add     al, byte ptr [eax]
0053921D   0000                   add     [eax], al

0053921F   000B                   add     [ebx], cl
00539221   7270                   jb      00539293
00539223   7447                   jz      0053926C
00539225   656E                   outsb
00539227   657269                 jb      00539293
0053922A   636FFC                 arpl    [edi-$04], bp
0053922D   0200                   add     al, byte ptr [eax]
0053922F   0001                   add     [ecx], al
00539231   000C51                 add     [ecx+edx*2], cl
00539234   52                     push    edx
00539235   53                     push    ebx
00539236   7562                   jnz     0053929A
00539238   44                     inc     esp
00539239   657461                 jz      0053929D
0053923C   696C320003000002       imul    ebp, [edx+esi+$00], $02000003
00539244   0007                   add     [edi], al
00539246   51                     push    ecx
00539247   52                     push    edx
00539248   42                     inc     edx
00539249   61                     popa
0053924A   6E                     outsb
0053924B   64310403               xor     fs:[ebx+eax], eax
0053924F   0000                   add     [eax], al

00539251   0300                   add     eax, [eax]
00539253   095152                 or      [ecx+$52], edx
00539256   4C                     dec     esp
00539257   61                     popa
00539258   62656C                 bound   esp, qword ptr [ebp+$6C]
0053925B   3136                   xor     [esi], esi
0053925D   0803                   or      [ebx], al
0053925F   0000                   add     [eax], al

00539261   0400                   add     al, +$00
00539263   085152                 or      [ecx+$52], dl
00539266   53                     push    ebx
00539267   6861706532             push    $32657061
0053926C   0C03                   or      al, $03
0053926E   0000                   add     [eax], al

00539270   0500085152             add     eax, +$52510800
00539275   47                     inc     edi
00539276   726F                   jb      005392E7
00539278   7570                   jnz     005392EA
0053927A   3110                   xor     [eax], edx
0053927C   0300                   add     eax, [eax]
0053927E   0003                   add     [ebx], al
00539280   0009                   add     [ecx], cl
00539282   51                     push    ecx
00539283   52                     push    edx
00539284   4C                     dec     esp
00539285   61                     popa
00539286   62656C                 bound   esp, qword ptr [ebp+$6C]
00539289   3137                   xor     [edi], esi
0053928B   1403                   adc     al, $03
0053928D   0000                   add     [eax], al

0053928F   0300                   add     eax, [eax]
00539291   095152                 or      [ecx+$52], edx
00539294   4C                     dec     esp
00539295   61                     popa
00539296   62656C                 bound   esp, qword ptr [ebp+$6C]
00539299   3138                   xor     [eax], edi
0053929B   1803                   sbb     [ebx], al
0053929D   0000                   add     [eax], al

0053929F   0400                   add     al, +$00
005392A1   085152                 or      [ecx+$52], dl
005392A4   53                     push    ebx
005392A5   6861706538             push    $38657061
005392AA   1C03                   sbb     al, $03
005392AC   0000                   add     [eax], al

005392AE   06                     push    es
005392AF   000A                   add     [edx], cl
005392B1   51                     push    ecx
005392B2   52                     push    edx
005392B3   44                     inc     esp
005392B4   42                     inc     edx
005392B5   54                     push    esp
005392B6   657874                 js      0053932D
005392B9   3137                   xor     [edi], esi
005392BB   2003                   and     [ebx], al
005392BD   0000                   add     [eax], al

005392BF   0300                   add     eax, [eax]
005392C1   095152                 or      [ecx+$52], edx
005392C4   4C                     dec     esp
005392C5   61                     popa
005392C6   62656C                 bound   esp, qword ptr [ebp+$6C]
005392C9   3139                   xor     [ecx], edi
005392CB   2403                   and     al, $03
005392CD   0000                   add     [eax], al

005392CF   0300                   add     eax, [eax]
005392D1   095152                 or      [ecx+$52], edx
005392D4   4C                     dec     esp
005392D5   61                     popa
005392D6   62656C                 bound   esp, qword ptr [ebp+$6C]
005392D9   3230                   xor     dh, byte ptr [eax]
005392DB   2803                   sub     [ebx], al
005392DD   0000                   add     [eax], al

005392DF   06                     push    es
005392E0   000A                   add     [edx], cl
005392E2   51                     push    ecx
005392E3   52                     push    edx
005392E4   44                     inc     esp
005392E5   42                     inc     edx
005392E6   54                     push    esp
005392E7   657874                 js      0053935E
005392EA   3138                   xor     [eax], edi
005392EC   2C03                   sub     al, $03
005392EE   0000                   add     [eax], al

*)
end;

procedure TfrmCadPessoa._PROC_005395CF(Sender : TObject);
begin
(*
005395CF   4D                     dec     ebp
005395D0   45                     inc     ebp
005395D1   52                     push    edx
005395D2   4F                     dec     edi
005395D3   D4                     aam
005395D4   0300                   add     eax, [eax]
005395D6   000A                   add     [edx], cl
005395D8   0017                   add     [edi], dl
005395DA   41                     inc     ecx
005395DB   44                     inc     esp
005395DC   4F                     dec     edi
005395DD   51                     push    ecx
005395DE   7279                   jb      00539659
005395E0   50                     push    eax
005395E1   657373                 jnb     00539657
005395E4   6F                     outsd
005395E5   61                     popa
005395E6   43                     inc     ebx
005395E7   4F                     dec     edi
005395E8   4D                     dec     ebp
005395E9   50                     push    eax
005395EA   4C                     dec     esp
005395EB   45                     inc     ebp
005395EC   4D                     dec     ebp
005395ED   45                     inc     ebp
005395EE   4E                     dec     esi
005395EF   54                     push    esp
005395F0   4F                     dec     edi
005395F1   D803                   fadd    dword ptr [ebx]
005395F3   0000                   add     [eax], al

005395F5   0A00                   or      al, byte ptr [eax]
005395F7   124144                 adc     al, byte ptr [ecx+$44]
005395FA   4F                     dec     edi
005395FB   51                     push    ecx
005395FC   7279                   jb      00539677
005395FE   50                     push    eax
005395FF   657373                 jnb     00539675
00539602   6F                     outsd
00539603   61                     popa
00539604   42                     inc     edx
00539605   41                     inc     ecx
00539606   49                     dec     ecx
00539607   52                     push    edx
00539608   52                     push    edx
00539609   4F                     dec     edi
0053960A   DC03                   fadd    qword ptr [ebx]
0053960C   0000                   add     [eax], al

0053960E   0A00                   or      al, byte ptr [eax]
00539610   124144                 adc     al, byte ptr [ecx+$44]
00539613   4F                     dec     edi
00539614   51                     push    ecx
00539615   7279                   jb      00539690
00539617   50                     push    eax
00539618   657373                 jnb     0053968E
0053961B   6F                     outsd
0053961C   61                     popa
0053961D   43                     inc     ebx
0053961E   49                     dec     ecx
0053961F   44                     inc     esp
00539620   41                     inc     ecx
00539621   44                     inc     esp
00539622   45                     inc     ebp
00539623   E003                   loopn   +$03
00539625   0000                   add     [eax], al

00539627   0A00                   or      al, byte ptr [eax]
00539629   0F41444F51             cmovno  eax, [edi+ecx*2+$51]
0053962E   7279                   jb      005396A9
00539630   50                     push    eax
00539631   657373                 jnb     005396A7
00539634   6F                     outsd
00539635   61                     popa
00539636   43                     inc     ebx
00539637   45                     inc     ebp
00539638   50                     push    eax
00539639   E403                   in      al, $03
0053963B   0000                   add     [eax], al

0053963D   0A00                   or      al, byte ptr [eax]
0053963F   0E                     push    cs
00539640   41                     inc     ecx
00539641   44                     inc     esp
00539642   4F                     dec     edi
00539643   51                     push    ecx
00539644   7279                   jb      005396BF
00539646   50                     push    eax
00539647   657373                 jnb     005396BD
0053964A   6F                     outsd
0053964B   61                     popa
0053964C   55                     push    ebp
0053964D   46                     inc     esi
0053964E   E80300000A             call    0A539656
00539653   0010                   add     [eax], dl
00539655   41                     inc     ecx
00539656   44                     inc     esp
00539657   4F                     dec     edi
00539658   51                     push    ecx
00539659   7279                   jb      005396D4
0053965B   50                     push    eax
0053965C   657373                 jnb     005396D2
0053965F   6F                     outsd
00539660   61                     popa
00539661   54                     push    esp
00539662   45                     inc     ebp
00539663   4C                     dec     esp
00539664   31EC                   xor     esp, ebp
00539666   0300                   add     eax, [eax]
00539668   000A                   add     [edx], cl
0053966A   0010                   add     [eax], dl
0053966C   41                     inc     ecx
0053966D   44                     inc     esp
0053966E   4F                     dec     edi
0053966F   51                     push    ecx
00539670   7279                   jb      005396EB
00539672   50                     push    eax
00539673   657373                 jnb     005396E9
00539676   6F                     outsd
00539677   61                     popa
00539678   54                     push    esp
00539679   45                     inc     ebp
0053967A   4C                     dec     esp
0053967B   32F0                   xor     dh, al
0053967D   0300                   add     eax, [eax]
0053967F   000A                   add     [edx], cl
00539681   0012                   add     [edx], dl
00539683   41                     inc     ecx
00539684   44                     inc     esp
00539685   4F                     dec     edi
00539686   51                     push    ecx
00539687   7279                   jb      00539702
00539689   50                     push    eax
0053968A   657373                 jnb     00539700
0053968D   6F                     outsd
0053968E   61                     popa
0053968F   54                     push    esp
00539690   49                     dec     ecx
00539691   54                     push    esp
00539692   55                     push    ebp
00539693   4C                     dec     esp
00539694   4F                     dec     edi
00539695   F4                     hlt
00539696   0300                   add     eax, [eax]
00539698   000C00                 add     [eax+eax], cl
0053969B   114144                 adc     [ecx+$44], eax
0053969E   4F                     dec     edi
0053969F   51                     push    ecx
005396A0   7279                   jb      0053971B
005396A2   50                     push    eax
005396A3   657373                 jnb     00539719
005396A6   6F                     outsd
005396A7   61                     popa
005396A8   53                     push    ebx
005396A9   45                     inc     ebp
005396AA   43                     inc     ebx
005396AB   41                     inc     ecx
005396AC   4F                     dec     edi
005396AD   F8                     clc
005396AE   0300                   add     eax, [eax]
005396B0   000C00                 add     [eax+eax], cl
005396B3   104144                 adc     [ecx+$44], al
005396B6   4F                     dec     edi
005396B7   51                     push    ecx
005396B8   7279                   jb      00539733
005396BA   50                     push    eax
005396BB   657373                 jnb     00539731
005396BE   6F                     outsd
005396BF   61                     popa
005396C0   5A                     pop     edx
005396C1   4F                     dec     edi
005396C2   4E                     dec     esi
005396C3   41                     inc     ecx
005396C4   FC                     cld
005396C5   0300                   add     eax, [eax]
005396C7   000A                   add     [edx], cl
005396C9   000E                   add     [esi], cl
005396CB   41                     inc     ecx
005396CC   44                     inc     esp
005396CD   4F                     dec     edi
005396CE   51                     push    ecx
005396CF   7279                   jb      0053974A
005396D1   50                     push    eax
005396D2   657373                 jnb     00539748
005396D5   6F                     outsd
005396D6   61                     popa
005396D7   52                     push    edx
005396D8   47                     inc     edi
005396D9   000400                 add     [eax+eax], al
005396DC   000A                   add     [edx], cl
005396DE   0011                   add     [ecx], dl
005396E0   41                     inc     ecx
005396E1   44                     inc     esp
005396E2   4F                     dec     edi
005396E3   51                     push    ecx
005396E4   7279                   jb      0053975F
005396E6   50                     push    eax
005396E7   657373                 jnb     0053975D
005396EA   6F                     outsd
005396EB   61                     popa
005396EC   4F                     dec     edi
005396ED   52                     push    edx
005396EE   47                     inc     edi
005396EF   41                     inc     ecx
005396F0   4F                     dec     edi
005396F1   0404                   add     al, +$04
005396F3   0000                   add     [eax], al

005396F5   0B00                   or      eax, [eax]
005396F7   114144                 adc     [ecx+$44], eax
005396FA   4F                     dec     edi
005396FB   51                     push    ecx
005396FC   7279                   jb      00539777
005396FE   50                     push    eax
005396FF   657373                 jnb     00539775
00539702   6F                     outsd
00539703   61                     popa
00539704   44                     inc     esp
00539705   54                     push    esp
00539706   45                     inc     ebp
00539707   58                     pop     eax
00539708   50                     push    eax
00539709   080400                 or      [eax+eax], al
0053970C   000A                   add     [edx], cl
0053970E   0010                   add     [eax], dl
00539710   41                     inc     ecx
00539711   44                     inc     esp
00539712   4F                     dec     edi
00539713   51                     push    ecx
00539714   7279                   jb      0053978F
00539716   50                     push    eax
00539717   657373                 jnb     0053978D
0053971A   6F                     outsd
0053971B   61                     popa
0053971C   43                     inc     ebx
0053971D   4E                     dec     esi
0053971E   50                     push    eax
0053971F   46                     inc     esi
00539720   0C04                   or      al, $04
00539722   0000                   add     [eax], al

00539724   0A00                   or      al, byte ptr [eax]
00539726   1441                   adc     al, $41
00539728   44                     inc     esp
00539729   4F                     dec     edi
0053972A   51                     push    ecx
0053972B   7279                   jb      005397A6
0053972D   50                     push    eax
0053972E   657373                 jnb     005397A4
00539731   6F                     outsd
00539732   61                     popa
00539733   45                     inc     ebp
00539734   53                     push    ebx
00539735   54                     push    esp
00539736   43                     inc     ebx
00539737   49                     dec     ecx
00539738   56                     push    esi
00539739   49                     dec     ecx
0053973A   4C                     dec     esp
0053973B   100400                 adc     [eax+eax], al
0053973E   000C00                 add     [eax+eax], cl
00539741   134144                 adc     eax, [ecx+$44]
00539744   4F                     dec     edi
00539745   51                     push    ecx
00539746   7279                   jb      005397C1
00539748   50                     push    eax
00539749   657373                 jnb     005397BF
0053974C   6F                     outsd
0053974D   61                     popa
0053974E   45                     inc     ebp
0053974F   53                     push    ebx
00539750   43                     inc     ebx
00539751   4F                     dec     edi
00539752   5F                     pop     edi
00539753   49                     dec     ecx
00539754   44                     inc     esp
00539755   1404                   adc     al, $04
00539757   0000                   add     [eax], al

00539759   0A00                   or      al, byte ptr [eax]
0053975B   114144                 adc     [ecx+$44], eax
0053975E   4F                     dec     edi
0053975F   51                     push    ecx
00539760   7279                   jb      005397DB
00539762   50                     push    eax
00539763   657373                 jnb     005397D9
00539766   6F                     outsd
00539767   61                     popa
00539768   45                     inc     ebp
00539769   4D                     dec     ebp
0053976A   41                     inc     ecx
0053976B   49                     dec     ecx
0053976C   4C                     dec     esp
0053976D   180400                 sbb     [eax+eax], al
00539770   000A                   add     [edx], cl
00539772   001441                 add     [ecx+eax*2], dl
00539775   44                     inc     esp
00539776   4F                     dec     edi
00539777   51                     push    ecx
00539778   7279                   jb      005397F3
0053977A   50                     push    eax
0053977B   657373                 jnb     005397F1
0053977E   6F                     outsd
0053977F   61                     popa
00539780   54                     push    esp
00539781   50                     push    eax
00539782   53                     push    ebx
00539783   41                     inc     ecx
00539784   4E                     dec     esi
00539785   47                     inc     edi
00539786   55                     push    ebp
00539787   45                     inc     ebp
00539788   1C04                   sbb     al, $04
0053978A   0000                   add     [eax], al

0053978C   0A00                   or      al, byte ptr [eax]
0053978E   0E                     push    cs
0053978F   41                     inc     ecx
00539790   44                     inc     esp
00539791   4F                     dec     edi
00539792   51                     push    ecx
00539793   7279                   jb      0053980E
00539795   50                     push    eax
00539796   657373                 jnb     0053980C
00539799   6F                     outsd
0053979A   61                     popa
0053979B   52                     push    edx
0053979C   48                     dec     eax
0053979D   200400                 and     [eax+eax], al
005397A0   000D000F4144           add     [$44410F00], cl
005397A6   4F                     dec     edi
005397A7   51                     push    ecx
005397A8   7279                   jb      00539823
005397AA   50                     push    eax
005397AB   657373                 jnb     00539821
005397AE   6F                     outsd
005397AF   61                     popa
005397B0   49                     dec     ecx
005397B1   55                     push    ebp
005397B2   46                     inc     esi
005397B3   2404                   and     al, $04
005397B5   0000                   add     [eax], al

005397B7   0300                   add     eax, [eax]
005397B9   095152                 or      [ecx+$52], edx
005397BC   4C                     dec     esp
005397BD   61                     popa
005397BE   62656C                 bound   esp, qword ptr [ebp+$6C]
005397C1   313428                 xor     [eax+ebp], esi
005397C4   0400                   add     al, +$00
005397C6   0006                   add     [esi], al
005397C8   0009                   add     [ecx], cl
005397CA   51                     push    ecx
005397CB   52                     push    edx
005397CC   44                     inc     esp
005397CD   42                     inc     edx
005397CE   54                     push    esp
005397CF   657874                 js      00539846
005397D2   382C04                 cmp     [esp+eax], ch
005397D5   0000                   add     [eax], al

005397D7   0300                   add     eax, [eax]
005397D9   095152                 or      [ecx+$52], edx
005397DC   4C                     dec     esp
005397DD   61                     popa
005397DE   62656C                 bound   esp, qword ptr [ebp+$6C]
005397E1   323430                 xor     dh, byte ptr [eax+esi]
005397E4   0400                   add     al, +$00
005397E6   0006                   add     [esi], al
005397E8   000A                   add     [edx], cl
005397EA   51                     push    ecx
005397EB   52                     push    edx
005397EC   44                     inc     esp
005397ED   42                     inc     edx
005397EE   54                     push    esp
005397EF   657874                 js      00539866
005397F2   313534040000           xor     [$00000434], esi
005397F8   0300                   add     eax, [eax]
005397FA   095152                 or      [ecx+$52], edx
005397FD   4C                     dec     esp
005397FE   61                     popa
005397FF   62656C                 bound   esp, qword ptr [ebp+$6C]
00539802   3236                   xor     dh, byte ptr [esi]
00539804   380400                 cmp     [eax+eax], al
00539807   0006                   add     [esi], al
00539809   000A                   add     [edx], cl
0053980B   51                     push    ecx
0053980C   52                     push    edx
0053980D   44                     inc     esp
0053980E   42                     inc     edx
0053980F   54                     push    esp
00539810   657874                 js      00539887
00539813   3232                   xor     dh, byte ptr [edx]
00539815   3C04                   cmp     al, $04
00539817   0000                   add     [eax], al

00539819   0300                   add     eax, [eax]
0053981B   095152                 or      [ecx+$52], edx
0053981E   4C                     dec     esp
0053981F   61                     popa
00539820   62656C                 bound   esp, qword ptr [ebp+$6C]
00539823   3237                   xor     dh, byte ptr [edi]
00539825   40                     inc     eax
00539826   0400                   add     al, +$00
00539828   0006                   add     [esi], al
0053982A   000A                   add     [edx], cl
0053982C   51                     push    ecx
0053982D   52                     push    edx
0053982E   44                     inc     esp
0053982F   42                     inc     edx
00539830   54                     push    esp
00539831   657874                 js      005398A8
00539834   323544040000           xor     dh, byte ptr [$00000444]
0053983A   0300                   add     eax, [eax]
0053983C   095152                 or      [ecx+$52], edx
0053983F   4C                     dec     esp
00539840   61                     popa
00539841   62656C                 bound   esp, qword ptr [ebp+$6C]
00539844   3238                   xor     bh, byte ptr [eax]
00539846   48                     dec     eax
00539847   0400                   add     al, +$00
00539849   0006                   add     [esi], al
0053984B   000A                   add     [edx], cl
0053984D   51                     push    ecx
0053984E   52                     push    edx
0053984F   44                     inc     esp
00539850   42                     inc     edx
00539851   54                     push    esp
00539852   657874                 js      005398C9
00539855   3237                   xor     dh, byte ptr [edi]
00539857   4C                     dec     esp
00539858   0400                   add     al, +$00
0053985A   0008                   add     [eax], cl
0053985C   0010                   add     [eax], dl
0053985E   41                     inc     ecx
0053985F   44                     inc     esp
00539860   4F                     dec     edi
00539861   51                     push    ecx
00539862   7279                   jb      005398DD
00539864   49                     dec     ecx
00539865   7465                   jz      005398CC
00539867   6D                     insd
00539868   50                     push    eax
00539869   657373                 jnb     005398DF
0053986C   6F                     outsd
0053986D   61                     popa
0053986E   50                     push    eax
0053986F   0400                   add     al, +$00
00539871   000E                   add     [esi], cl
00539873   001B                   add     [ebx], bl
00539875   41                     inc     ecx
00539876   44                     inc     esp
00539877   4F                     dec     edi
00539878   51                     push    ecx
00539879   7279                   jb      005398F4
0053987B   49                     dec     ecx
0053987C   7465                   jz      005398E3
0053987E   6D                     insd
0053987F   50                     push    eax
00539880   657373                 jnb     005398F6
00539883   6F                     outsd
00539884   61                     popa
00539885   49                     dec     ecx
00539886   54                     push    esp
00539887   45                     inc     ebp
00539888   4D                     dec     ebp
00539889   5F                     pop     edi
0053988A   50                     push    eax
0053988B   45                     inc     ebp
0053988C   53                     push    ebx
0053988D   53                     push    ebx
0053988E   4F                     dec     edi
0053988F   41                     inc     ecx
00539890   54                     push    esp
00539891   0400                   add     al, +$00
00539893   0009                   add     [ecx], cl
00539895   0019                   add     [ecx], bl
00539897   41                     inc     ecx
00539898   44                     inc     esp
00539899   4F                     dec     edi
0053989A   51                     push    ecx
0053989B   7279                   jb      00539916
0053989D   49                     dec     ecx
0053989E   7465                   jz      00539905
005398A0   6D                     insd
005398A1   50                     push    eax
005398A2   657373                 jnb     00539918
005398A5   6F                     outsd
005398A6   61                     popa
005398A7   50                     push    eax
005398A8   45                     inc     ebp
005398A9   53                     push    ebx
005398AA   53                     push    ebx
005398AB   4F                     dec     edi
005398AC   41                     inc     ecx
005398AD   5F                     pop     edi
005398AE   49                     dec     ecx
005398AF   44                     inc     esp
005398B0   58                     pop     eax
005398B1   0400                   add     al, +$00
005398B3   0009                   add     [ecx], cl
005398B5   001A                   add     [edx], bl
005398B7   41                     inc     ecx
005398B8   44                     inc     esp
005398B9   4F                     dec     edi
005398BA   51                     push    ecx
005398BB   7279                   jb      00539936
005398BD   49                     dec     ecx
005398BE   7465                   jz      00539925
005398C0   6D                     insd
005398C1   50                     push    eax
005398C2   657373                 jnb     00539938
005398C5   6F                     outsd
005398C6   61                     popa
005398C7   54                     push    esp
005398C8   49                     dec     ecx
005398C9   50                     push    eax
005398CA   4F                     dec     edi
005398CB   5F                     pop     edi
005398CC   53                     push    ebx
005398CD   4F                     dec     edi
005398CE   4C                     dec     esp
005398CF   43                     inc     ebx
005398D0   49                     dec     ecx
005398D1   5C                     pop     esp
005398D2   0400                   add     al, +$00
005398D4   000B                   add     [ebx], cl
005398D6   001E                   add     [esi], bl
005398D8   41                     inc     ecx
005398D9   44                     inc     esp
005398DA   4F                     dec     edi
005398DB   51                     push    ecx
005398DC   7279                   jb      00539957
005398DE   49                     dec     ecx
005398DF   7465                   jz      00539946
005398E1   6D                     insd
005398E2   50                     push    eax
005398E3   657373                 jnb     00539959
005398E6   6F                     outsd
005398E7   61                     popa
005398E8   44                     inc     esp
005398E9   54                     push    esp
005398EA   5F                     pop     edi
005398EB   53                     push    ebx
005398EC   4F                     dec     edi
005398ED   4C                     dec     esp
005398EE   49                     dec     ecx
005398EF   43                     inc     ebx
005398F0   49                     dec     ecx
005398F1   54                     push    esp
005398F2   41                     inc     ecx
005398F3   43                     inc     ebx
005398F4   41                     inc     ecx
005398F5   4F                     dec     edi
005398F6   60                     pusha
005398F7   0400                   add     al, +$00
005398F9   000B                   add     [ebx], cl
005398FB   0018                   add     [eax], bl
005398FD   41                     inc     ecx
005398FE   44                     inc     esp
005398FF   4F                     dec     edi
00539900   51                     push    ecx
00539901   7279                   jb      0053997C
00539903   49                     dec     ecx
00539904   7465                   jz      0053996B
00539906   6D                     insd
00539907   50                     push    eax
00539908   657373                 jnb     0053997E
0053990B   6F                     outsd
0053990C   61                     popa
0053990D   44                     inc     esp
0053990E   54                     push    esp
0053990F   5F                     pop     edi
00539910   41                     inc     ecx
00539911   54                     push    esp
00539912   45                     inc     ebp
00539913   4E                     dec     esi
00539914   44                     inc     esp
00539915   640400                 add     al, +$00
00539918   000A                   add     [edx], cl
0053991A   001B                   add     [ebx], bl
0053991C   41                     inc     ecx
0053991D   44                     inc     esp
0053991E   4F                     dec     edi
0053991F   51                     push    ecx
00539920   7279                   jb      0053999B
00539922   49                     dec     ecx
00539923   7465                   jz      0053998A
00539925   6D                     insd
00539926   50                     push    eax
00539927   657373                 jnb     0053999D
0053992A   6F                     outsd
0053992B   61                     popa
0053992C   41                     inc     ecx
0053992D   54                     push    esp
0053992E   45                     inc     ebp
0053992F   4E                     dec     esi
00539930   44                     inc     esp
00539931   49                     dec     ecx
00539932   4D                     dec     ebp
00539933   45                     inc     ebp
00539934   4E                     dec     esi
00539935   54                     push    esp
00539936   4F                     dec     edi
00539937   6804000009             push    $09000004
0053993C   0017                   add     [edi], dl
0053993E   41                     inc     ecx
0053993F   44                     inc     esp
00539940   4F                     dec     edi
00539941   51                     push    ecx
00539942   7279                   jb      005399BD
00539944   49                     dec     ecx
00539945   7465                   jz      005399AC
00539947   6D                     insd
00539948   50                     push    eax
00539949   657373                 jnb     005399BF
0053994C   6F                     outsd
0053994D   61                     popa
0053994E   46                     inc     esi
0053994F   55                     push    ebp
00539950   4E                     dec     esi
00539951   43                     inc     ebx
00539952   5F                     pop     edi
00539953   49                     dec     ecx
00539954   44                     inc     esp
00539955   6C                     insb
00539956   0400                   add     al, +$00
00539958   000A                   add     [edx], cl
0053995A   0017                   add     [edi], dl
0053995C   41                     inc     ecx
0053995D   44                     inc     esp
0053995E   4F                     dec     edi
0053995F   51                     push    ecx
00539960   7279                   jb      005399DB
00539962   49                     dec     ecx
00539963   7465                   jz      005399CA
00539965   6D                     insd
00539966   50                     push    eax
00539967   657373                 jnb     005399DD
0053996A   6F                     outsd
0053996B   61                     popa
0053996C   53                     push    ebx
0053996D   4F                     dec     edi
0053996E   4C                     dec     esp
0053996F   55                     push    ebp
00539970   43                     inc     ebx
00539971   41                     inc     ecx
00539972   4F                     dec     edi
00539973   7004                   jo      00539979
00539975   0000                   add     [eax], al

00539977   0900                   or      [eax], eax
00539979   184144                 sbb     [ecx+$44], al
0053997C   4F                     dec     edi
0053997D   51                     push    ecx
0053997E   7279                   jb      005399F9
00539980   49                     dec     ecx
00539981   7465                   jz      005399E8
00539983   6D                     insd
00539984   50                     push    eax
00539985   657373                 jnb     005399FB
00539988   6F                     outsd
00539989   61                     popa
0053998A   4C                     dec     esp
0053998B   4F                     dec     edi
0053998C   43                     inc     ebx
0053998D   41                     inc     ecx
0053998E   4C                     dec     esp
0053998F   5F                     pop     edi
00539990   49                     dec     ecx
00539991   44                     inc     esp
00539992   7404                   jz      00539998
00539994   0000                   add     [eax], al

00539996   0D001C4144             or      eax, $44411C00
0053999B   4F                     dec     edi
0053999C   51                     push    ecx
0053999D   7279                   jb      00539A18
0053999F   49                     dec     ecx
005399A0   7465                   jz      00539A07
005399A2   6D                     insd
005399A3   50                     push    eax
005399A4   657373                 jnb     00539A1A
005399A7   6F                     outsd
005399A8   61                     popa
005399A9   69736F6C756369         imul    esi, [ebx+$6F], $6963756C
005399B0   7461                   jz      00539A13
005399B2   63616F                 arpl    [ecx+$6F], sp
005399B5   7804                   js      005399BB
005399B7   0000                   add     [eax], al

005399B9   0D001C4144             or      eax, $44411C00
005399BE   4F                     dec     edi
005399BF   51                     push    ecx
005399C0   7279                   jb      00539A3B
005399C2   49                     dec     ecx
005399C3   7465                   jz      00539A2A
005399C5   6D                     insd
005399C6   50                     push    eax
005399C7   657373                 jnb     00539A3D
005399CA   6F                     outsd
005399CB   61                     popa
005399CC   6966756E63696F         imul    esp, [esi+$75], $6F69636E
005399D3   6E                     outsb
005399D4   61                     popa
005399D5   7269                   jb      00539A40
005399D7   6F                     outsd
005399D8   7C04                   jl      005399DE
005399DA   0000                   add     [eax], al

005399DC   0D00164144             or      eax, $44411600
005399E1   4F                     dec     edi
005399E2   51                     push    ecx
005399E3   7279                   jb      00539A5E
005399E5   49                     dec     ecx
005399E6   7465                   jz      00539A4D
005399E8   6D                     insd
005399E9   50                     push    eax
005399EA   657373                 jnb     00539A60
005399ED   6F                     outsd
005399EE   61                     popa
005399EF   696C6F63616C8004       imul    ebp, [edi+ebp*2+$63], $04806C61
005399F7   0000                   add     [eax], al

005399F9   06                     push    es
005399FA   0009                   add     [ecx], cl
005399FC   51                     push    ecx
005399FD   52                     push    edx
005399FE   44                     inc     esp
005399FF   42                     inc     edx
00539A00   54                     push    esp
00539A01   657874                 js      00539A78
00539A04   31840400000600         xor     [esp+eax+$60000], eax
00539A0B   095152                 or      [ecx+$52], edx
00539A0E   44                     inc     esp
00539A0F   42                     inc     edx
00539A10   54                     push    esp
00539A11   657874                 js      00539A88
00539A14   32880400000F           xor     cl, byte ptr [eax+$F000004]
00539A1A   0007                   add     [edi], al
00539A1C   51                     push    ecx
00539A1D   52                     push    edx
00539A1E   45                     inc     ebp
00539A1F   7870                   js      00539A91
00539A21   7231                   jb      00539A54
00539A23   8C0400                 mov     word ptr [eax+eax], es
00539A26   0006                   add     [esi], al
00539A28   0009                   add     [ecx], cl
00539A2A   51                     push    ecx
00539A2B   52                     push    edx
00539A2C   44                     inc     esp
00539A2D   42                     inc     edx
00539A2E   54                     push    esp
00539A2F   657874                 js      00539AA6
00539A32   33900400000A           xor     edx, [eax+$A000004]
00539A38   001B                   add     [ebx], bl
00539A3A   41                     inc     ecx
00539A3B   44                     inc     esp
00539A3C   4F                     dec     edi
00539A3D   51                     push    ecx
00539A3E   7279                   jb      00539AB9
00539A40   49                     dec     ecx
00539A41   7465                   jz      00539AA8
00539A43   6D                     insd
00539A44   50                     push    eax
00539A45   657373                 jnb     00539ABB
00539A48   6F                     outsd
00539A49   61                     popa
00539A4A   53                     push    ebx
00539A4B   4F                     dec     edi
00539A4C   4C                     dec     esp
00539A4D   49                     dec     ecx
00539A4E   43                     inc     ebx
00539A4F   49                     dec     ecx
00539A50   54                     push    esp
00539A51   41                     inc     ecx
00539A52   43                     inc     ebx
00539A53   41                     inc     ecx
00539A54   4F                     dec     edi
00539A55   94                     xchg    eax, esp
00539A56   0400                   add     al, +$00
00539A58   0006                   add     [esi], al
00539A5A   0009                   add     [ecx], cl
00539A5C   51                     push    ecx
00539A5D   52                     push    edx
00539A5E   44                     inc     esp
00539A5F   42                     inc     edx
00539A60   54                     push    esp
00539A61   657874                 js      00539AD8
00539A64   3598040000             xor     eax, $00000498
00539A69   0F0007                 sldt    word ptr [edi]
00539A6C   51                     push    ecx
00539A6D   52                     push    edx
00539A6E   45                     inc     ebp
00539A6F   7870                   js      00539AE1
00539A71   7232                   jb      00539AA5
00539A73   9C                     pushf   
00539A74   0400                   add     al, +$00
00539A76   0003                   add     [ebx], al
00539A78   0008                   add     [eax], cl
00539A7A   51                     push    ecx
00539A7B   52                     push    edx
00539A7C   4C                     dec     esp
00539A7D   61                     popa
00539A7E   62656C                 bound   esp, qword ptr [ebp+$6C]
00539A81   33A004000003           xor     esp, [eax+$3000004]
00539A87   0008                   add     [eax], cl
00539A89   51                     push    ecx
00539A8A   52                     push    edx
00539A8B   4C                     dec     esp
00539A8C   61                     popa
00539A8D   62656C                 bound   esp, qword ptr [ebp+$6C]
00539A90   34A4                   xor     al, $A4
00539A92   0400                   add     al, +$00
00539A94   0003                   add     [ebx], al
00539A96   0008                   add     [eax], cl
00539A98   51                     push    ecx
00539A99   52                     push    edx
00539A9A   4C                     dec     esp
00539A9B   61                     popa
00539A9C   62656C                 bound   esp, qword ptr [ebp+$6C]
00539A9F   31A804000010           xor     [eax+$10000004], ebp
00539AA5   000B                   add     [ebx], cl
00539AA7   44                     inc     esp
00539AA8   61                     popa
00539AA9   7461                   jz      00539B0C
00539AAB   53                     push    ebx
00539AAC   6F                     outsd
00539AAD   7572                   jnz     00539B21
00539AAF   636531                 arpl    [ebp+$31], sp
00539AB2   0C54                   or      al, $54
00539AB4   66726D                 jb      00539B24
00539AB7   52                     push    edx
00539AB8   656C                   insb
00539ABA   52                     push    edx
00539ABB   6F                     outsd
00539ABC   7374                   jnb     00539B32
00539ABE   6F                     outsd
00539ABF   1100                   adc     [eax], eax
00539AC1   CC                     int     3
00539AC2   3652                   push    edx
00539AC4   00D4                   add     ah, dl
00539AC6   2D52003028             sub     eax, $28300052
00539ACB   52                     push    edx
00539ACC   008023530068           add     [eax+$68005323], al
00539AD2   325300                 xor     dl, byte ptr [ebx+$00]
00539AD5   383B                   cmp     [ebx], bh
00539AD7   52                     push    edx
00539AD8   00C8                   add     al, cl
00539ADA   2653                   push    ebx
00539ADC   00C0                   add     al, al
00539ADE   2E53                   push    ebx
00539AE0   00602E                 add     [eax+$2E], ah
00539AE3   50                     push    eax
00539AE4   00C4                   add     ah, al
00539AE6   AA                     stosb
00539AE7   49                     dec     ecx
00539AE8   0074A749               add     [edi+$49], dh
00539AEC   004CB749               add     [edi+esi*4+$49], cl
00539AF0   0068AC                 add     [eax-$54], ch
00539AF3   49                     dec     ecx
00539AF4   0088A54900C8           add     [eax+$C80049A5], cl
00539AFA   B049                   mov     al, $49
00539AFC   00742A53               add     [edx+ebp+$53], dh
00539B00   00E0                   add     al, ah
00539B02   DA4900                 fimul   dword ptr [ecx+$00]
00539B05   8D4000                 lea     eax, [eax+$00]
00539B08   0C9B                   or      al, $9B
00539B0A   53                     push    ebx
00539B0B   0007                   add     [edi], al
00539B0D   0C54                   or      al, $54
00539B0F   66726D                 jb      00539B7F
00539B12   52                     push    edx
00539B13   656C                   insb
00539B15   52                     push    edx
00539B16   6F                     outsd
00539B17   7374                   jnb     00539B8D
00539B19   6F                     outsd
00539B1A   20915300985C           and     [ecx+$5C980053], dl
00539B20   48                     dec     eax
00539B21   005E00                 add     [esi+$00], bl
00539B24   0C55                   or      al, $55
00539B26   6E                     outsb
00539B27   697452656C526F73       imul    esi, [edx+edx*2+$65], $736F526C
00539B2F   746F                   jz      00539BA0
00539B31   0000                   add     [eax], al

00539B33   90                     nop
00539B34   55                     push    ebp
00539B35   8BEC                   mov     ebp, esp
00539B37   33C0                   xor     eax, eax
00539B39   55                     push    ebp
00539B3A   68599B5300             push    $00539B59

***** TRY
|
00539B3F   64FF30                 push    dword ptr fs:[eax]
00539B42   648920                 mov     fs:[eax], esp
00539B45   FF058CC15400           inc     dword ptr [$0054C18C]
00539B4B   33C0                   xor     eax, eax
00539B4D   5A                     pop     edx
00539B4E   59                     pop     ecx
00539B4F   59                     pop     ecx
00539B50   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ŒÁT'
|
00539B53   68609B5300             push    $00539B60
00539B58   C3                     ret


* Reference to: System.@HandleFinally;
|
00539B59   E91EA0ECFF             jmp     00403B7C
00539B5E   EBF8                   jmp     00539B58

****** END
|
00539B60   5D                     pop     ebp
00539B61   C3                     ret

00539B62   8BC0                   mov     eax, eax
00539B64   832D8CC1540001         sub     dword ptr [$0054C18C], +$01
00539B6B   C3                     ret

00539B6C   B89B530000             mov     eax, $0000539B
00539B71   0000                   add     [eax], al

00539B73   0000                   add     [eax], al

00539B75   0000                   add     [eax], al

00539B77   0000                   add     [eax], al

00539B79   0000                   add     [eax], al

00539B7B   000CA0                 add     [eax], cl
00539B7E   53                     push    ebx
00539B7F   00AC9C53000000         add     [esp+ebx*4+$0053], ch
00539B86   0000                   add     [eax], al

00539B88   0000                   add     [eax], al

00539B8A   0000                   add     [eax], al

00539B8C   D6                     DB  $D6  //
00539B8D   9F                     lahf
00539B8E   53                     push    ebx
00539B8F   00B40300005C69         add     [ebx+eax+$695C0000], dh
00539B96   53                     push    ebx
00539B97   00CC                   add     ah, cl
00539B99   6E                     outsb
00539B9A   42                     inc     edx
00539B9B   00AC884800608A         add     [eax+ecx*4+$8A600048], ch
00539BA2   48                     dec     eax
00539BA3   00443640               add     [esi+esi+$40], al
00539BA7   00CC                   add     ah, cl
00539BA9   AE                     scasb
00539BAA   48                     dec     eax
00539BAB   00803340009C           add     [eax+$9C004033], al
00539BB1   334000                 xor     eax, [eax+$00]
00539BB4   C88A                   enter   , $8A
00539BB6   48                     dec     eax
00539BB7   0028                   add     [eax], ch
00539BB9   6747                   inc     edi
00539BBB   0038                   add     [eax], bh
00539BBD   90                     nop
00539BBE   48                     dec     eax
00539BBF   0064E741               add     [edi+$41], ah
00539BC3   00888C4800C4           add     [eax+$C400488C], cl
00539BC9   8C4800                 mov     word ptr [eax+$00], cs
00539BCC   D08D4800F8EF           ror     byte ptr [ebp+$EFF80048], 1
00539BD2   46                     inc     esi
00539BD3   00E4                   add     ah, ah
00539BD5   6E                     outsb
00539BD6   42                     inc     edx
00539BD7   004896                 add     [eax-$6A], cl
00539BDA   48                     dec     eax
00539BDB   00C4                   add     ah, al
00539BDD   6B4200E8               imul    eax, [edx+$00], $E8
00539BE1   D14800                 ror     dword ptr [eax+$00], 1
00539BE4   208748003C62           and     [edi+$623C0048], al
00539BEA   47                     inc     edi
00539BEB   005867                 add     [eax+$67], bl
00539BEE   47                     inc     edi
00539BEF   00A46647002CE5         add     [esi+$E52C0047], ah
00539BF6   46                     inc     esi
00539BF7   00B85C470028           add     [eax+$2800475C], bh
00539BFD   93                     xchg    eax, ebx
00539BFE   48                     dec     eax
00539BFF   00B859470074           add     [eax+$74004759], bh
00539C05   E446                   in      al, $46
00539C07   0078E4                 add     [eax-$1C], bh
00539C0A   46                     inc     esi
00539C0B   001C94                 add     [esp+edx*4], bl
00539C0E   48                     dec     eax
00539C0F   0010                   add     [eax], dl
00539C11   154700E0EF             adc     eax, $EFE00047
00539C16   46                     inc     esi
00539C17   00F0                   add     al, dh
00539C19   E546                   in      eax, $46
00539C1B   006CF146               add     [ecx+esi*8+$46], ch
00539C1F   0010                   add     [eax], dl
00539C21   96                     xchg    eax, esi
00539C22   48                     dec     eax
00539C23   00DC                   add     ah, bl
00539C25   94                     xchg    eax, esp
00539C26   48                     dec     eax
00539C27   00A4F246008896         add     [edx+esi*8+$96880046], ah
00539C2E   48                     dec     eax
00539C2F   0094154700445A         add     [ebp+edx+$5A440047], dl
00539C36   47                     inc     edi
00539C37   0000                   add     [eax], al

*)
end;

end.